debug-mode: false
db:
  url: mariadb
  driver: org.mariadb.jdbc.Driver
  debug: true
  max-pool-size: 6
  ip: localhost
  port: 3306
  user: root
  password: null
  database: faction
spawners:
  ZOMBIE: 50000
  SKELETON: 100000
  IRON_GOLEM: 150000
  CREEPER: 250000
  SNOWMAN: 200000
  VILLAGER: 300000