name: heros-spawner
version: ${project.version}
main: net.herospvp.herosspawner.HerosSpawner
authors: [ Niketion ]
softdepend:
  - HolographicDisplays
  - database-lib
  - heros-core
commands:
  spawner:
  collector:
  top:
    aliases: [ftop]
